#Set
my_set = {1,2,3,4,5,5} # duplicates are not allowed
my_set.add(123)
my_set.add(3)
print(my_set)

#covert list to set
my_list = [1,1,2,3,4,4]
print(my_list)
print(set(my_list))

# set object doesn't support indexing

#difference()
new_set = {1,2}
print(my_set)
print(my_set.difference(new_set))

#discard()
print(new_set)
new_set.discard(2)
print(new_set)



#Scroll to bottom to see solution
# You are working for the school Principal. We have a database of school students:
school = {'Bobby','Tammy','Jammy','Sally','Danny'}

#during class, the teachers take attendance and compile it into a list. 
attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']

#using what you learned about sets, create a piece of code that the school principal can use to immediately find out who missed class so they can call the parents. (Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers + the school database to use python and make his/her job easier): Find the students that miss class!

#Solution: Notice how we don't have to convert the attendance_list to a set...it does it for you.
#print(school.difference(attendance_list))
